### PR TITLE
dragable components in side menu

### PR DESCRIPTION
**Pull request by Varcho**

### CODE REVIEW

**Comment by Varcho** [comment]
Visual Demo:
http://web.cse.ohio-state.edu/~varcho.5/animation2.gif

**Comment by Varcho** [comment]
@dltn if you need help implementing dragging this diff integrates DnD + flux in our application, and could be useful reference.

**Comment by 3ygun** [comment]
From the `.gif` we should probably merge #46 first before this one

**Comment by dltn** [comment]
You rock @Varcho !

**Pull request merged**
