### PR TITLE
Fix Rendering of MC questions

### PR DESCRIPTION
**Pull request by 3ygun**
# Goal

Fix the parsing of MC questions and learn regex expressions :tada: Completes major parts of #38!

**NOTE**: [regex101.com](https://regex101.com) is the best project ever!

# Parts

- [x] Fixed MC parsing in the following cases:
  - [x] Stored at end of prompt (ex: `3-questions.pdf`)
  - [x] Stored in next question prompt (ex: `3-3-questions--1-of-each-type.pdf`)
  - [x] Mix of the above ^ (ex: `hp_1.pdf`)
  - [x] Has different format then the usual one we used `a. Trump` as `A: Trump` (ex: `harry.pdf`)
- [x] Fixed conjoined questions issue (ex: `harry.pdf`)
  - e.g. All questions are in a single prompt
- [x] Adds debugging information to the console

Visualized:

watsonta--fixed-mc-rendering-hp_1

# Ignores

- Issues presented in `example-of-all-our-desired-things.pdf` namely
  - What if a question prompts sentence ends in the matched style of the regex. e.g. it ends in `dad. What?` which will be incorrectly split.
- Rendering of less than 4 MC questions

Shown here:
watsonta--remaining-issues

### CODE REVIEW

**Comment by 3ygun** [comment]
~Fixing conflicts now~
- [x] Resolved

**Comment by 3ygun** [comment]
Conflicts are fixed. Changes retested with current master.

**Review by dltn — COMMENTED** [review]
Does django / etc automatically import `re`?

Definitely not a concern for tomorrow, but for engineering's sake: no support for 3 / 5 / 6 / ... choice multiple choice questions

**Comment by 3ygun** [comment]
Does django / etc automatically import re?
- Probably not, but we do! Just off the top of the diff see the [full file](https://github.com/signofthehorns/watson-ta/blob/69381e11f26bb72a8279f1232a42fb0bd71e516b/www/api/views/upload_questions.py)

Definitely not a concern for tomorrow, but for engineering's sake: no support for 3 / 5 / 6 / ... choice multiple choice questions
- Agreed, should make this dynamic, it wouldn't be too hard... but I think it'd be better for a different PR

**Pull request merged**
